# Generated by Django 4.2 on 2024-10-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_alter_user_is_seller_alter_user_is_shopper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
