# Generated by Django 4.2 on 2024-10-17 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_orderitem_name_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email_address', models.CharField(max_length=255, verbose_name='Email Address')),
                ('address', models.TextField(verbose_name='Email Address')),
                ('zipcode', models.CharField(max_length=255, verbose_name='Email Address')),
                ('city', models.CharField(max_length=255, verbose_name='Email Address')),
                ('country', models.CharField(max_length=255, verbose_name='Email Address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Shipping Info',
                'verbose_name_plural': 'Shipping Info',
            },
        ),
    ]
