# Generated by Django 4.2 on 2024-10-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_shippinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='order',
        ),
    ]
