# Generated by Django 4.2 on 2024-10-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_order_shipping_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='zipcode',
            field=models.CharField(max_length=255, verbose_name='Zip Code'),
        ),
    ]
